# -*- coding: utf-8 -*-
"""HW 05-Comfortable_Words.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12hGTyK16HCVt5QawVtXaR6DGLnknvVzV

A comfortable word is a word which you can type always alternating the hand you 
ype with (assuming you type using a Q-keyboard and use of the ten-fingers standard).
The word will always be a string consisting of only letters from a to z.
Write a program which returns True if it's a comfortable word or False otherwise.
For Example:word===>>tester===>> False
"""

left=set("qwertasdfgbvcxz")
right=set("uıopğüişlkjmöçyhn")
word=str(input("bir kelime giriniz:"))
letters=set(word)

print(letters)
print(bool(letters.intersection(right) and letters.intersection(left)))