# -*- coding: utf-8 -*-
"""HW 06-Password_Reminder.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z0kABBRXd3A2qmoeyJl9gkpIrUhrfmAB

Let's say; you left a message in the past that prints a password you need. 
To see the password you wrote, you need to enter your name and the program should recognize you.
Write a program that Takes the first name from the user and compares it to yours,
Then if the name the user entered is the same as yours, print out such as : "Hello, Joseph! The password is : W@12",
If the name the user entered is not the same as yours, print out such as : "Hello, Amina! See you later.
"""

your_name = input("Please enter your first name: ")
your_name = your_name.capitalize()
my_name = "Barıs"
password = "W@12"
if your_name == my_name:
    print("Hello", your_name, "\b!", "The password is: ", password)
else:
    print("Hello", your_name, "\b!", "See you later.")